---
version: 1

name: officectl
description: A tool to manage a directory of people over multiple sources (LDAP, Google, etc.)
homepage: https://github.com/happn-app/officectl/

maintainer: François Lamboley <francois.lamboley@happn.com>

source:
  url: NONE
  arch-mapping:
    amd64: amd64

control:
  depends:
    - libldap-2.4-2
    - libssl1.0.2
    - swiftlang-libs (=5.2.2-RELEASE-1~mkdeb1)
    - zlib1g
  description: |
    Not much to say here…
  section: admin

install:
  recipe:
    /etc/officectl:
      - pattern: default_config.yaml
        rename: officectl.yaml
        conffile: true
    /lib/systemd/system:
      - pattern: systemd
        rename: officectl.service
    /etc/init.d:
      - pattern: initd
        rename: officectl
        conffile: true
  upstream:
    /usr/bin:
      - pattern: officectl
    /usr/share/officectl:
      - pattern: "*/*"

dirs:
  - /var/lib/officectl/
  - /var/log/officectl/
  - /var/run/officectl/

# vim: ts=2 sw=2 et
