# Don’t forget to change Swift version in recipe too when changing here.
FROM happn/swift-builder:5.1.1-RELEASE

RUN apt-get update && apt-get install -y --no-install-recommends \
  libldap2-dev \
  libncurses-dev \
  libssl1.0-dev \
  pkg-config \
  zlib1g-dev
