# Don’t forget to change Swift version in recipe too when changing here.
FROM happn/swift-builder:5.2.4-RELEASE_operationqueue-patch

RUN apt-get update && apt-get install -y --no-install-recommends \
  libldap2-dev \
  libncurses-dev \
  libssl-dev \
  pkg-config \
  zlib1g-dev
