/*
 * !!! File autogenerated by convert_email_xml_inputs_to_swift.swift
 * !!! Don’t change manually.
 *
 * EmailTests.swift
 * OfficeKitTests
 *
 * Created by convert_email_xml_inputs_to_swift.swift on 3/26/19.
 */

import XCTest
@testable import OfficeKit



class EmailTests : XCTestCase {
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId1() {
		let nonLossyASCIIEmail = ""
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errNodomain)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId2() {
		let nonLossyASCIIEmail = "test"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errNodomain)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId3() {
		let nonLossyASCIIEmail = "@"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errNolocalpart)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId4() {
		let nonLossyASCIIEmail = "test@"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errNodomain)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId5() {
		let nonLossyASCIIEmail = "test@io"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId6() {
		let nonLossyASCIIEmail = "@io"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errNolocalpart)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId7() {
		let nonLossyASCIIEmail = "@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errNolocalpart)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId8() {
		let nonLossyASCIIEmail = "test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId9() {
		let nonLossyASCIIEmail = "test@nominet.org.uk"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId10() {
		let nonLossyASCIIEmail = "test@about.museum"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId11() {
		let nonLossyASCIIEmail = "a@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId12() {
		let nonLossyASCIIEmail = "test@e.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId13() {
		let nonLossyASCIIEmail = "test@iana.a"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId14() {
		let nonLossyASCIIEmail = "test.test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId15() {
		let nonLossyASCIIEmail = ".test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errDotStart)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId16() {
		let nonLossyASCIIEmail = "test.@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errDotEnd)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId17() {
		let nonLossyASCIIEmail = "test..iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errConsecutivedots)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId18() {
		let nonLossyASCIIEmail = "test_exa-mple.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errNodomain)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId19() {
		let nonLossyASCIIEmail = "!#$%&`*+/=?^`{|}~@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId20() {
		let nonLossyASCIIEmail = "test\\\\@test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId21() {
		let nonLossyASCIIEmail = "123@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId22() {
		let nonLossyASCIIEmail = "test@123.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId23() {
		let nonLossyASCIIEmail = "test@iana.123"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Tldnumeric)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId24() {
		let nonLossyASCIIEmail = "test@255.255.255.255"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Tldnumeric)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId25() {
		let nonLossyASCIIEmail = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghiklm@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId26() {
		let nonLossyASCIIEmail = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghiklmn@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322LocalToolong)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId27() {
		let nonLossyASCIIEmail = "test@abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId28() {
		let nonLossyASCIIEmail = "test@abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghiklm.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322LabelToolong)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId29() {
		let nonLossyASCIIEmail = "test@mason-dixon.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId30() {
		let nonLossyASCIIEmail = "test@-iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errDomainhyphenstart)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId31() {
		let nonLossyASCIIEmail = "test@iana-.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errDomainhyphenend)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId32() {
		let nonLossyASCIIEmail = "test@c--n.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId33() {
		let nonLossyASCIIEmail = "test@iana.co-uk"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId34() {
		let nonLossyASCIIEmail = "test@.iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errDotStart)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId35() {
		let nonLossyASCIIEmail = "test@iana.org."
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errDotEnd)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId36() {
		let nonLossyASCIIEmail = "test@iana..com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errConsecutivedots)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId37() {
		let nonLossyASCIIEmail = "a@a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId38() {
		let nonLossyASCIIEmail = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghiklm@abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId39() {
		let nonLossyASCIIEmail = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghiklm@abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Toolong)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId40() {
		let nonLossyASCIIEmail = "a@abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefg.hij"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Toolong)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId41() {
		let nonLossyASCIIEmail = "a@abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefg.hijk"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322DomainToolong)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId42() {
		let nonLossyASCIIEmail = "\"test\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Quotedstring)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId43() {
		let nonLossyASCIIEmail = "\"\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Quotedstring)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId44() {
		let nonLossyASCIIEmail = "\"\"\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId45() {
		let nonLossyASCIIEmail = "\"\\\\a\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Quotedstring)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId46() {
		let nonLossyASCIIEmail = "\"\\\\\"\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Quotedstring)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId47() {
		let nonLossyASCIIEmail = "\"\\\\\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedquotedstr)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId48() {
		let nonLossyASCIIEmail = "\"\\\\\\\\\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Quotedstring)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId49() {
		let nonLossyASCIIEmail = "test\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId50() {
		let nonLossyASCIIEmail = "\"test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedquotedstr)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId51() {
		let nonLossyASCIIEmail = "\"test\"test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errAtextAfterQs)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId52() {
		let nonLossyASCIIEmail = "test\"text\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId53() {
		let nonLossyASCIIEmail = "\"test\"\"test\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId54() {
		let nonLossyASCIIEmail = "\"test\".\"test\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecLocalpart)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId55() {
		let nonLossyASCIIEmail = "\"test\\\\ test\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Quotedstring)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId56() {
		let nonLossyASCIIEmail = "\"test\".test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecLocalpart)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId57() {
		let nonLossyASCIIEmail = "\"test\\u2400\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingQtext)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId58() {
		let nonLossyASCIIEmail = "\"test\\\\\\u2400\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecQp)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId59() {
		let nonLossyASCIIEmail = "\"abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghj\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322LocalToolong)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId60() {
		let nonLossyASCIIEmail = "\"abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefg\\\\h\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322LocalToolong)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId61() {
		let nonLossyASCIIEmail = "test@[255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Addressliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId62() {
		let nonLossyASCIIEmail = "test@a[255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId63() {
		let nonLossyASCIIEmail = "test@[255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Domainliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId64() {
		let nonLossyASCIIEmail = "test@[255.255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Domainliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId65() {
		let nonLossyASCIIEmail = "test@[255.255.255.256]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Domainliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId66() {
		let nonLossyASCIIEmail = "test@[1111:2222:3333:4444:5555:6666:7777:8888]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Domainliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId67() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666:7777]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Grpcount)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId68() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666:7777:8888]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Addressliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId69() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666:7777:8888:9999]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Grpcount)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId70() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666:7777:888G]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Badchar)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId71() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666::8888]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .rfc5321Ipv6Deprecated)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId72() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555::8888]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Addressliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId73() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666::7777:8888]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Maxgrps)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId74() {
		let nonLossyASCIIEmail = "test@[IPv6::3333:4444:5555:6666:7777:8888]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Colonstrt)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId75() {
		let nonLossyASCIIEmail = "test@[IPv6:::3333:4444:5555:6666:7777:8888]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Addressliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId76() {
		let nonLossyASCIIEmail = "test@[IPv6:1111::4444:5555::8888]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv62X2Xcolon)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId77() {
		let nonLossyASCIIEmail = "test@[IPv6:::]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Addressliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId78() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Grpcount)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId79() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666:255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Addressliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId80() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666:7777:255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Grpcount)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId81() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444::255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Addressliteral)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId82() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:5555:6666::255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Maxgrps)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId83() {
		let nonLossyASCIIEmail = "test@[IPv6:1111:2222:3333:4444:::255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv62X2Xcolon)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId84() {
		let nonLossyASCIIEmail = "test@[IPv6::255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Colonstrt)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId85() {
		let nonLossyASCIIEmail = " test @iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecCfwsNearAt)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId86() {
		let nonLossyASCIIEmail = "test@ iana .com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecCfwsNearAt)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId87() {
		let nonLossyASCIIEmail = "test . test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecFws)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId88() {
		let nonLossyASCIIEmail = "\\u240d\\u240a test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsFws)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId89() {
		let nonLossyASCIIEmail = "\\u240d\\u240a \\u240d\\u240a test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecFws)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId90() {
		let nonLossyASCIIEmail = "(comment)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsComment)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId91() {
		let nonLossyASCIIEmail = "((comment)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedcomment)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId92() {
		let nonLossyASCIIEmail = "(comment(comment))test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsComment)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId93() {
		let nonLossyASCIIEmail = "test@(comment)iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecCfwsNearAt)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId94() {
		let nonLossyASCIIEmail = "test(comment)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errAtextAfterCfws)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId95() {
		let nonLossyASCIIEmail = "test@(comment)[255.255.255.255]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecCfwsNearAt)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId96() {
		let nonLossyASCIIEmail = "(comment)abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghiklm@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsComment)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId97() {
		let nonLossyASCIIEmail = "test@(comment)abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghikl.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecCfwsNearAt)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId98() {
		let nonLossyASCIIEmail = "(comment)test@abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghik.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghik.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.abcdefghijklmnopqrstuvwxyzabcdefghijk.abcdefghijklmnopqrstu"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsComment)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId99() {
		let nonLossyASCIIEmail = "test@iana.org\\u240a"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId100() {
		let nonLossyASCIIEmail = "test@xn--hxajbheg2az3al.xn--jxalpdlp"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId101() {
		let nonLossyASCIIEmail = "xn--test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId102() {
		let nonLossyASCIIEmail = "test@iana.org-"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errDomainhyphenend)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId103() {
		let nonLossyASCIIEmail = "\"test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedquotedstr)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId104() {
		let nonLossyASCIIEmail = "(test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedcomment)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId105() {
		let nonLossyASCIIEmail = "test@(iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedcomment)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId106() {
		let nonLossyASCIIEmail = "test@[1.2.3.4"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUncloseddomlit)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId107() {
		let nonLossyASCIIEmail = "\"test\\\\\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedquotedstr)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId108() {
		let nonLossyASCIIEmail = "(comment\\\\)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedcomment)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId109() {
		let nonLossyASCIIEmail = "test@iana.org(comment\\\\)"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUnclosedcomment)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId110() {
		let nonLossyASCIIEmail = "test@iana.org(comment\\\\"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errBackslashend)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId112() {
		let nonLossyASCIIEmail = "test@[RFC-5322-domain-literal]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Domainliteral)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId113() {
		let nonLossyASCIIEmail = "test@[RFC-5322]-domain-literal]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errAtextAfterDomlit)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId114() {
		let nonLossyASCIIEmail = "test@[RFC-5322-[domain-literal]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingDtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId115() {
		let nonLossyASCIIEmail = "test@[RFC-5322-\\\\\\u2407-domain-literal]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322DomlitObsdtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId116() {
		let nonLossyASCIIEmail = "test@[RFC-5322-\\\\\\u2409-domain-literal]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322DomlitObsdtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId117() {
		let nonLossyASCIIEmail = "test@[RFC-5322-\\\\]-domain-literal]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322DomlitObsdtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId118() {
		let nonLossyASCIIEmail = "test@[RFC-5322-domain-literal\\\\]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errUncloseddomlit)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId119() {
		let nonLossyASCIIEmail = "test@[RFC-5322-domain-literal\\\\"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errBackslashend)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId120() {
		let nonLossyASCIIEmail = "test@[RFC 5322 domain literal]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Domainliteral)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId121() {
		let nonLossyASCIIEmail = "test@[RFC-5322-domain-literal] (comment)"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Domainliteral)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId122() {
		let nonLossyASCIIEmail = "\\177@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId123() {
		let nonLossyASCIIEmail = "test@\\177.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId124() {
		let nonLossyASCIIEmail = "\"\\177\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecQtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId125() {
		let nonLossyASCIIEmail = "\"\\\\\\177\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecQp)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId126() {
		let nonLossyASCIIEmail = "(\\177)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecCtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId127() {
		let nonLossyASCIIEmail = "test@iana.org\\u240d"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errCrNoLf)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId128() {
		let nonLossyASCIIEmail = "\\u240dtest@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errCrNoLf)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId129() {
		let nonLossyASCIIEmail = "\"\\u240dtest\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errCrNoLf)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId130() {
		let nonLossyASCIIEmail = "(\\u240d)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errCrNoLf)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId131() {
		let nonLossyASCIIEmail = "test@iana.org(\\u240d)"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errCrNoLf)
	}
	
	/* From Michael Rushton (https://squiloople.com/tag/email/) */
	func testXMLTestId132() {
		let nonLossyASCIIEmail = "\\u240atest@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId133() {
		let nonLossyASCIIEmail = "\"\\u240a\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingQtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId134() {
		let nonLossyASCIIEmail = "\"\\\\\\u240a\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecQp)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId135() {
		let nonLossyASCIIEmail = "(\\u240a)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingCtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId136() {
		let nonLossyASCIIEmail = "\\u2407@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId137() {
		let nonLossyASCIIEmail = "test@\\u2407.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingAtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId138() {
		let nonLossyASCIIEmail = "\"\\u2407\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecQtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId139() {
		let nonLossyASCIIEmail = "\"\\\\\\u2407\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecQp)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId140() {
		let nonLossyASCIIEmail = "(\\u2407)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecCtext)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId141() {
		let nonLossyASCIIEmail = "\\u240d\\u240atest@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfEnd)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId142() {
		let nonLossyASCIIEmail = "\\u240d\\u240a \\u240d\\u240atest@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfEnd)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId143() {
		let nonLossyASCIIEmail = " \\u240d\\u240atest@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfEnd)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId144() {
		let nonLossyASCIIEmail = " \\u240d\\u240a test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsFws)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId145() {
		let nonLossyASCIIEmail = " \\u240d\\u240a \\u240d\\u240atest@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfEnd)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId146() {
		let nonLossyASCIIEmail = " \\u240d\\u240a\\u240d\\u240atest@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfX2)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId147() {
		let nonLossyASCIIEmail = " \\u240d\\u240a\\u240d\\u240a test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfX2)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId148() {
		let nonLossyASCIIEmail = "test@iana.org\\u240d\\u240a "
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsFws)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId149() {
		let nonLossyASCIIEmail = "test@iana.org\\u240d\\u240a \\u240d\\u240a "
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecFws)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId150() {
		let nonLossyASCIIEmail = "test@iana.org\\u240d\\u240a"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfEnd)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId151() {
		let nonLossyASCIIEmail = "test@iana.org\\u240d\\u240a \\u240d\\u240a"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfEnd)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId152() {
		let nonLossyASCIIEmail = "test@iana.org \\u240d\\u240a"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfEnd)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId153() {
		let nonLossyASCIIEmail = "test@iana.org \\u240d\\u240a "
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsFws)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId154() {
		let nonLossyASCIIEmail = "test@iana.org \\u240d\\u240a \\u240d\\u240a"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfEnd)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId155() {
		let nonLossyASCIIEmail = "test@iana.org \\u240d\\u240a\\u240d\\u240a"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfX2)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId156() {
		let nonLossyASCIIEmail = "test@iana.org \\u240d\\u240a\\u240d\\u240a "
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errFwsCrlfX2)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId157() {
		let nonLossyASCIIEmail = " test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsFws)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId158() {
		let nonLossyASCIIEmail = "test@iana.org "
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .cfws)
		XCTAssertEqual(validationResult, .cfwsFws)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId159() {
		let nonLossyASCIIEmail = "test@[IPv6:1::2:]"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Ipv6Colonend)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId160() {
		let nonLossyASCIIEmail = "\"test\\\\\\251\"@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .err)
		XCTAssertEqual(validationResult, .errExpectingQpair)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId161() {
		let nonLossyASCIIEmail = "test@iana/icann.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5322)
		XCTAssertEqual(validationResult, .rfc5322Domain)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId165() {
		let nonLossyASCIIEmail = "test.(comment)test@iana.org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .deprec)
		XCTAssertEqual(validationResult, .deprecComment)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId166() {
		let nonLossyASCIIEmail = "test@org"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .rfc5321)
		XCTAssertEqual(validationResult, .rfc5321Tld)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId167() {
		let nonLossyASCIIEmail = "test@test.com"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
	/* From Dominic Sayers (https://isemail.info) */
	func testXMLTestId168() {
		let nonLossyASCIIEmail = "test@nic.no"
		let email = String(data: Data(nonLossyASCIIEmail.utf8), encoding: .nonLossyASCII)!
		let validationResult = Email.evaluateEmail(email, checkDNS: false)
		XCTAssertEqual(validationResult.category, .validCategory)
		XCTAssertEqual(validationResult, .valid)
	}
	
}
