#if !canImport(ObjectiveC)
import XCTest

extension FutureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureTests = [
        ("testWaitAll1", testWaitAll1),
    ]
}

extension LDAPOperationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LDAPOperationTests = [
        ("test1_LDAPObjectCreation", test1_LDAPObjectCreation),
        ("test2_LDAPObjectRetrieval", test2_LDAPObjectRetrieval),
    ]
}

extension LDAPSearchQueryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LDAPSearchQueryTests = [
        ("testAttributeDescriptionInstantiation1", testAttributeDescriptionInstantiation1),
        ("testAttributeDescriptionInstantiation2", testAttributeDescriptionInstantiation2),
        ("testAttributeDescriptionInstantiation3", testAttributeDescriptionInstantiation3),
        ("testInvalidAttributeDescriptionInstantiation0", testInvalidAttributeDescriptionInstantiation0),
        ("testInvalidAttributeDescriptionInstantiation1", testInvalidAttributeDescriptionInstantiation1),
        ("testInvalidAttributeDescriptionInstantiation2", testInvalidAttributeDescriptionInstantiation2),
        ("testInvalidAttributeDescriptionInstantiation3", testInvalidAttributeDescriptionInstantiation3),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FutureTests.__allTests__FutureTests),
        testCase(LDAPOperationTests.__allTests__LDAPOperationTests),
        testCase(LDAPSearchQueryTests.__allTests__LDAPSearchQueryTests),
    ]
}
#endif
