import XCTest

extension EmailTests {
    static let __allTests = [
        ("testXMLTestId1", testXMLTestId1),
        ("testXMLTestId10", testXMLTestId10),
        ("testXMLTestId100", testXMLTestId100),
        ("testXMLTestId101", testXMLTestId101),
        ("testXMLTestId102", testXMLTestId102),
        ("testXMLTestId103", testXMLTestId103),
        ("testXMLTestId104", testXMLTestId104),
        ("testXMLTestId105", testXMLTestId105),
        ("testXMLTestId106", testXMLTestId106),
        ("testXMLTestId107", testXMLTestId107),
        ("testXMLTestId108", testXMLTestId108),
        ("testXMLTestId109", testXMLTestId109),
        ("testXMLTestId11", testXMLTestId11),
        ("testXMLTestId110", testXMLTestId110),
        ("testXMLTestId112", testXMLTestId112),
        ("testXMLTestId113", testXMLTestId113),
        ("testXMLTestId114", testXMLTestId114),
        ("testXMLTestId115", testXMLTestId115),
        ("testXMLTestId116", testXMLTestId116),
        ("testXMLTestId117", testXMLTestId117),
        ("testXMLTestId118", testXMLTestId118),
        ("testXMLTestId119", testXMLTestId119),
        ("testXMLTestId12", testXMLTestId12),
        ("testXMLTestId120", testXMLTestId120),
        ("testXMLTestId121", testXMLTestId121),
        ("testXMLTestId122", testXMLTestId122),
        ("testXMLTestId123", testXMLTestId123),
        ("testXMLTestId124", testXMLTestId124),
        ("testXMLTestId125", testXMLTestId125),
        ("testXMLTestId126", testXMLTestId126),
        ("testXMLTestId127", testXMLTestId127),
        ("testXMLTestId128", testXMLTestId128),
        ("testXMLTestId129", testXMLTestId129),
        ("testXMLTestId13", testXMLTestId13),
        ("testXMLTestId130", testXMLTestId130),
        ("testXMLTestId131", testXMLTestId131),
        ("testXMLTestId132", testXMLTestId132),
        ("testXMLTestId133", testXMLTestId133),
        ("testXMLTestId134", testXMLTestId134),
        ("testXMLTestId135", testXMLTestId135),
        ("testXMLTestId136", testXMLTestId136),
        ("testXMLTestId137", testXMLTestId137),
        ("testXMLTestId138", testXMLTestId138),
        ("testXMLTestId139", testXMLTestId139),
        ("testXMLTestId14", testXMLTestId14),
        ("testXMLTestId140", testXMLTestId140),
        ("testXMLTestId141", testXMLTestId141),
        ("testXMLTestId142", testXMLTestId142),
        ("testXMLTestId143", testXMLTestId143),
        ("testXMLTestId144", testXMLTestId144),
        ("testXMLTestId145", testXMLTestId145),
        ("testXMLTestId146", testXMLTestId146),
        ("testXMLTestId147", testXMLTestId147),
        ("testXMLTestId148", testXMLTestId148),
        ("testXMLTestId149", testXMLTestId149),
        ("testXMLTestId15", testXMLTestId15),
        ("testXMLTestId150", testXMLTestId150),
        ("testXMLTestId151", testXMLTestId151),
        ("testXMLTestId152", testXMLTestId152),
        ("testXMLTestId153", testXMLTestId153),
        ("testXMLTestId154", testXMLTestId154),
        ("testXMLTestId155", testXMLTestId155),
        ("testXMLTestId156", testXMLTestId156),
        ("testXMLTestId157", testXMLTestId157),
        ("testXMLTestId158", testXMLTestId158),
        ("testXMLTestId159", testXMLTestId159),
        ("testXMLTestId16", testXMLTestId16),
        ("testXMLTestId160", testXMLTestId160),
        ("testXMLTestId161", testXMLTestId161),
        ("testXMLTestId165", testXMLTestId165),
        ("testXMLTestId166", testXMLTestId166),
        ("testXMLTestId167", testXMLTestId167),
        ("testXMLTestId168", testXMLTestId168),
        ("testXMLTestId17", testXMLTestId17),
        ("testXMLTestId18", testXMLTestId18),
        ("testXMLTestId19", testXMLTestId19),
        ("testXMLTestId2", testXMLTestId2),
        ("testXMLTestId20", testXMLTestId20),
        ("testXMLTestId21", testXMLTestId21),
        ("testXMLTestId22", testXMLTestId22),
        ("testXMLTestId23", testXMLTestId23),
        ("testXMLTestId24", testXMLTestId24),
        ("testXMLTestId25", testXMLTestId25),
        ("testXMLTestId26", testXMLTestId26),
        ("testXMLTestId27", testXMLTestId27),
        ("testXMLTestId28", testXMLTestId28),
        ("testXMLTestId29", testXMLTestId29),
        ("testXMLTestId3", testXMLTestId3),
        ("testXMLTestId30", testXMLTestId30),
        ("testXMLTestId31", testXMLTestId31),
        ("testXMLTestId32", testXMLTestId32),
        ("testXMLTestId33", testXMLTestId33),
        ("testXMLTestId34", testXMLTestId34),
        ("testXMLTestId35", testXMLTestId35),
        ("testXMLTestId36", testXMLTestId36),
        ("testXMLTestId37", testXMLTestId37),
        ("testXMLTestId38", testXMLTestId38),
        ("testXMLTestId39", testXMLTestId39),
        ("testXMLTestId4", testXMLTestId4),
        ("testXMLTestId40", testXMLTestId40),
        ("testXMLTestId41", testXMLTestId41),
        ("testXMLTestId42", testXMLTestId42),
        ("testXMLTestId43", testXMLTestId43),
        ("testXMLTestId44", testXMLTestId44),
        ("testXMLTestId45", testXMLTestId45),
        ("testXMLTestId46", testXMLTestId46),
        ("testXMLTestId47", testXMLTestId47),
        ("testXMLTestId48", testXMLTestId48),
        ("testXMLTestId49", testXMLTestId49),
        ("testXMLTestId5", testXMLTestId5),
        ("testXMLTestId50", testXMLTestId50),
        ("testXMLTestId51", testXMLTestId51),
        ("testXMLTestId52", testXMLTestId52),
        ("testXMLTestId53", testXMLTestId53),
        ("testXMLTestId54", testXMLTestId54),
        ("testXMLTestId55", testXMLTestId55),
        ("testXMLTestId56", testXMLTestId56),
        ("testXMLTestId57", testXMLTestId57),
        ("testXMLTestId58", testXMLTestId58),
        ("testXMLTestId59", testXMLTestId59),
        ("testXMLTestId6", testXMLTestId6),
        ("testXMLTestId60", testXMLTestId60),
        ("testXMLTestId61", testXMLTestId61),
        ("testXMLTestId62", testXMLTestId62),
        ("testXMLTestId63", testXMLTestId63),
        ("testXMLTestId64", testXMLTestId64),
        ("testXMLTestId65", testXMLTestId65),
        ("testXMLTestId66", testXMLTestId66),
        ("testXMLTestId67", testXMLTestId67),
        ("testXMLTestId68", testXMLTestId68),
        ("testXMLTestId69", testXMLTestId69),
        ("testXMLTestId7", testXMLTestId7),
        ("testXMLTestId70", testXMLTestId70),
        ("testXMLTestId71", testXMLTestId71),
        ("testXMLTestId72", testXMLTestId72),
        ("testXMLTestId73", testXMLTestId73),
        ("testXMLTestId74", testXMLTestId74),
        ("testXMLTestId75", testXMLTestId75),
        ("testXMLTestId76", testXMLTestId76),
        ("testXMLTestId77", testXMLTestId77),
        ("testXMLTestId78", testXMLTestId78),
        ("testXMLTestId79", testXMLTestId79),
        ("testXMLTestId8", testXMLTestId8),
        ("testXMLTestId80", testXMLTestId80),
        ("testXMLTestId81", testXMLTestId81),
        ("testXMLTestId82", testXMLTestId82),
        ("testXMLTestId83", testXMLTestId83),
        ("testXMLTestId84", testXMLTestId84),
        ("testXMLTestId85", testXMLTestId85),
        ("testXMLTestId86", testXMLTestId86),
        ("testXMLTestId87", testXMLTestId87),
        ("testXMLTestId88", testXMLTestId88),
        ("testXMLTestId89", testXMLTestId89),
        ("testXMLTestId9", testXMLTestId9),
        ("testXMLTestId90", testXMLTestId90),
        ("testXMLTestId91", testXMLTestId91),
        ("testXMLTestId92", testXMLTestId92),
        ("testXMLTestId93", testXMLTestId93),
        ("testXMLTestId94", testXMLTestId94),
        ("testXMLTestId95", testXMLTestId95),
        ("testXMLTestId96", testXMLTestId96),
        ("testXMLTestId97", testXMLTestId97),
        ("testXMLTestId98", testXMLTestId98),
        ("testXMLTestId99", testXMLTestId99),
    ]
}

extension FutureTests {
    static let __allTests = [
        ("testWaitAll1", testWaitAll1),
    ]
}

extension LDAPOperationTests {
    static let __allTests = [
        ("test1_LDAPObjectCreation", test1_LDAPObjectCreation),
        ("test2_LDAPObjectRetrieval", test2_LDAPObjectRetrieval),
    ]
}

extension LDAPSearchQueryTests {
    static let __allTests = [
        ("testAttributeDescriptionInstantiation1", testAttributeDescriptionInstantiation1),
        ("testAttributeDescriptionInstantiation2", testAttributeDescriptionInstantiation2),
        ("testAttributeDescriptionInstantiation3", testAttributeDescriptionInstantiation3),
        ("testInvalidAttributeDescriptionInstantiation0", testInvalidAttributeDescriptionInstantiation0),
        ("testInvalidAttributeDescriptionInstantiation1", testInvalidAttributeDescriptionInstantiation1),
        ("testInvalidAttributeDescriptionInstantiation2", testInvalidAttributeDescriptionInstantiation2),
        ("testInvalidAttributeDescriptionInstantiation3", testInvalidAttributeDescriptionInstantiation3),
    ]
}

#if !os(macOS)
public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EmailTests.__allTests),
        testCase(FutureTests.__allTests),
        testCase(LDAPOperationTests.__allTests),
        testCase(LDAPSearchQueryTests.__allTests),
    ]
}
#endif
