#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          officectl
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage directories from multiple sources (LDAP, Google, etc.)
# Description:       Manage directories from multiple sources (LDAP, Google, etc.)
### END INIT INFO

NAME="officectl"
DESC="Manage directories from multiple sources (LDAP, Google, etc.)"
USER="officectl"
GROUP="officectl"

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON=/usr/bin/$NAME
DAEMON_ARGS="server serve"

LOGFILE="/var/log/officectl/officectl.log"
PIDFILE="/var/run/officectl/officectl.pid"

HELPER="/usr/bin/daemon"
HELPER_ARGS="--name=$NAME --output=$LOGFILE --pidfile=$PIDFILE --user=$USER:$GROUP"

do_start_prepare() {
    install -d 0755 -o $USER -g $GROUP $(dirname $PIDFILE)
}

do_start_cmd() {
    $HELPER $HELPER_ARGS --running && return 1
    $HELPER $HELPER_ARGS -- $DAEMON $DAEMON_ARGS || return 2
}

do_stop_cmd() {
    $HELPER $HELPER_ARGS --running || return 1
    $HELPER $HELPER_ARGS --stop || return 2
    sleep 2s
    $HELPER $HELPER_ARGS --running && return 2
}
